# Generated by Django 6.0.1 on 2026-06-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_report_carton_size_report_collection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='images_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
